### ISSUE TITLE
Landscape mode doesn’t work even after update to 1.1.4

### ISSUE THREAD

**Issue by iA7myd** [jacksight/xina520_official_jailbreak#13]
Still have this issue on my iPhone 12 Pro Max iOS 15.1.1, I hope you fix it soon guys..

**Comment by ChrisGleich1AufsMaul** [comment]
Same here (iPad Air 4; A14; iOS 15.0.2)

**Comment by jacksight** [comment]
Check out https://github.com/jacksight/xina520_official_jailbreak/issues/16
