### ISSUE TITLE
ipados 15.6 m1 support

### ISSUE THREAD

**Issue by Aljeksandr** [jacksight/xina520_official_jailbreak#15]
expectation or not real?

**Comment by Aljeksandr** [comment]
when can I test it?

**Comment by NotDarkn** [comment]
XinaA15 does not support iOS 15.6 at the moment, and no jailbreak supports the M1 iPad on iOS 15.6 at the moment either.
Please keep waiting for a jailbreak to appear that is compatible with your device and verison.
