### ISSUE TITLE
关于改字体的一个小问题请浪哥注意一下，谢谢了。

### ISSUE THREAD

**Issue by heyanjiang** [jacksight/xina520_official_jailbreak#17]
目前虽然可以修改系统字体，但是safari浏览器的默认读取字体位置仍然是系统的system,library,font，于是造成了基于safari的豆瓣，知乎，甚至微信的回复区仍然是系统默认的苹方字体，非常违和，希望浪哥看看，有没有方法把safari的字体指向修改后的路径，就能彻底解决字体问题了，谢谢您！

**Comment by jacksight** [comment]
这个是已知问题 之后会修正
