### ISSUE TITLE
关于RocketBootstrap Mach-lookup Deny的问题

### ISSUE THREAD

**Issue by xuan32546** [jacksight/xina520_official_jailbreak#19]
Jacksight和浪哥你们好，目前使用浪哥的源下载的RocketBootstrap还是会导致沙盒进程（backboardd）mach-lookup失败，具体错误信息如下: 
```Sandbox: backboardd(4079) deny(1) mach-lookup lh:rbs:rockettest_messageport```

示例代码如下（来自于RocketBootstrap [wiki](https://iphonedev.wiki/index.php/RocketBootstrap)）：
```
CFMessagePortRef remote = rocketbootstrap_cfmessageportcreateremote(kCFAllocatorDefault, CFSTR("rockettest_messageport"));
if (!remote) {
// 永远会走到这里并打印出上面的错误信息
    NSLog(@"init remote port failed");
    return ;
}
```

请问Jacksight和浪哥是否知晓这个问题，或者是我的什么操作有问题吗？谢谢！

**Comment by jacksight** [comment]
他应该已经知晓这个问题了 目前这不算重大问题 我们会陆续处里
