### ISSUE TITLE
Hacked dpkg does not support binary install scripts

### ISSUE THREAD

**Issue by sbingner** [jacksight/xina520_official_jailbreak#21]
Dpkg seems to be hacked to sign all binaries during installation, but it does not sign binary install scripts - so they don't work.

I also don't see the dpkg source anywhere...

**Comment by jacksight** [comment]
Got it, I'll report it to xina

**Comment by HuChundong** [comment]
> 

it‘s a known issue before 1.1.5. but it's not in high priority.
