### ISSUE TITLE
越狱设置黑屏

### ISSUE THREAD

**Issue by zzhtsyz** [jacksight/xina520_official_jailbreak#3]
越狱以后设置页面
13promax 系统15.0.2

**Comment by zzhtsyz** [comment]
![Uploading EBC43D0D-1BDD-41E1-8415-405326DB4FDF.png…]()

**Comment by jacksight** [comment]
看不到你上传的照片

**Comment by zzhtsyz** [comment]
![Uploading E0060FA1-8F20-4EB1-BAF8-DED6888397FB.png…]()

**Comment by zzhtsyz** [comment]
![Uploading DFB03464-EAF8-49A0-95B4-4B47190E66D1.png…]()

**Comment by zzhtsyz** [comment]
![image](https://user-images.githubusercontent.com/15843440/206851360-93053455-0c50-4da3-a4fd-4c9610efbea1.png)
