### ISSUE TITLE
[BUG] Device tends to reboot randomly more often using 1.1.6.2

### ISSUE THREAD

**Issue by NotDarkn** [jacksight/xina520_official_jailbreak#33]
**Device:** iPhone 11 (Pro)
**iOS:** `15.1
**XinaA15 Version:** 1.1.6.2

Upon rejailbreaking with XinaA15 1.1.6.2 and having multiple tweaks, the device tends to reboot randomly. 

For example, the device could start rebooting randomly after rejailbreaking. May it be 5 minutes after rejailbreaking, or 1 and a half days after rejailbreaking. It's completely inconsistent and gets quite annoying.

Another example is when you do an action, the device could randomly reboot: 
- If you try to snap a photo, the device could reboot. 
- If you try to facetime somebody, the device could reboot. 
- If you try to turn on the flashlight, the device could reboot. 
- If you try to send a message, the device could reboot.

It's quite annoying with how random these reboots happen, which is why I'm reporting this as a bug.

**Comment by jacksight** [comment]
Are there any tweaks installed? Any logs?
