### ISSUE TITLE
[BUG] If you have apps like iCleaner or Filza installed and they're in their own folder and then rejailbreak, they appear outside of their folder and appear in their own folder.

### ISSUE THREAD

**Issue by NotDarkn** [jacksight/xina520_official_jailbreak#34]
**Device:** iPhone 11 (Pro)
**iOS:** `15.1
**XinaA15 Version:** 1.1.6.2

Reading off the title might seem a bit confusing so I'll clarify a bit more here.

Lets say that you have the tweak Filza and iCleaner, they're both apps so they'll appear on the home screen. Now lets say that you also put them in their own folder called "Jailbreak", on that session with XinaA15 they will stay in that folder and stay in the same place.

Then lets say that you reboot your phone and have to rejailbreak with XinaA15, this is when some weird issue occurs. After rejailbreaking and check your home screen, you'll see that the iCleaner and Filza apps are outside of their original place. They are also both in their own folders now, not in the same one. The folders for both of them still say "Jailbreak", however there are now 2 "Jailbreak" folders, 1 of them consisting with Filza, 1 of them consisting with iCleaner.

This seems to only happen with the 2 most recently installed apps on XinaA15 from what I've seen, so yeah that's that.

**Comment by jacksight** [comment]
Contact tweaks developers for this issue
