### ISSUE TITLE
[BUG] Automatic Rotation seems to break due to random ldrestarts when device is inactive

### ISSUE THREAD

**Issue by NotDarkn** [jacksight/xina520_official_jailbreak#37]
**Device:** iPhone 11 (Pro)
**iOS:** `15.1
**XinaA15 Version:** 1.1.6.2

When rejailbreaking with XinaA15, it seems to have really random issues, for example:

The device tends to randomly ldrestart when the device goes inactive.

This is quite annoying, as ldestart seems to break rotation on the device.

**Comment by yousefahmed134** [comment]
Device: iPhone 11 (Pro Max)
iOS: 15.1
XinaA15 Version: 1.1.6.2

I have a similar issue the device randomly restarts and I had to re-jailbreak

automatic rotation breaks after jailbreak

**Comment by reosx** [comment]
Has anyone found a solution to this problem? Or why it randomly reboots/unjailbreaks?

**Comment by jacksight** [comment]
This is not a major issue, will not be fixed immediately
