### ISSUE TITLE
自带files无法访问samba共享

### ISSUE THREAD

**Issue by 439qi** [jacksight/xina520_official_jailbreak#4]
![4DC4585A-DA73-408B-8AFB-1017F7DF2863](https://user-images.githubusercontent.com/33175770/206835902-d8009350-ab98-4cc7-b609-a576adf30011.png)
iPhone13 ios15.0
越狱后自带的files访问samba共享文件夹会出错

**Comment by jacksight** [comment]
先暂时用其他app来连线
