### ISSUE TITLE
Apple File Conduit 2 tweak crashes the jailbreak installation

### ISSUE THREAD

**Issue by EnekoT2001** [jacksight/xina520_official_jailbreak#40]
I basically manually installed all the dependencies it needed since for some reason sileo couldn't: Ldid and libplist3, those don't break anything, but the moment I install apple file conduit 2 from sileo or manually through dpkg commands and I respring, it goes into safe mode, it always does until removed.

Uninstalling it doesn't fully work because it leaves it as half-uninstalled, it gets rid of the safe mode boot though, dpkg says to reinstall it before trying to uninstall it but reinstalling doesn't do anything, I have to go and manually delete the specific entries on '/var/lib/dpkg/status' so the system thinks there's nothing going on about this. I don't know why this specific tweak makes it crash but I thought it was worth mentioning.

**Comment by jacksight** [comment]
Apple file conduit won't work on XinaA15, do not attempt to install it
