### ISSUE TITLE
Running SSH server - even it's disabled in XIna App in jailbreak 

### ISSUE THREAD

**Issue by rozzimann96** [jacksight/xina520_official_jailbreak#46]
Hi, I noticed this already few months a go. **THIS IS SERIOUS SECURITY THREAD!**
Even when I toogle off "Open SSH server" and hit Open jailbreak, SSH is actually started and you can successfully login to device.

Pls solve it. 😕  
<img width="304" alt="Snímek obrazovky 2023-03-03 v 0 27 55" src="https://user-images.githubusercontent.com/43329213/222588642-c564f96b-21ea-4da1-9041-d780654d5ccc.png">
<img width="662" alt="Snímek obrazovky 2023-03-03 v 0 29 10" src="https://user-images.githubusercontent.com/43329213/222588649-0f4c1915-7f91-425f-8658-e3a6e97647c8.png">

**Comment by jacksight** [comment]
Got it, it's been reported
