### ISSUE TITLE
[BUG] Chinese text files causes unicode issues

### ISSUE THREAD

**Issue by NotDarkn** [jacksight/xina520_official_jailbreak#48]
**Device**: iPhone 11 (Pro)
**iOS**: `15.1
**XinaA15 Version:** 1.1.7.1
***
When you use a Chinese file name for asset files, unicode can sometimes bug out and then corrupt the file names. This can cause in the UI looking completely gray and have missing assets that just say "Button."

Changing these assets to use an English file name would fix and eliminate these issues completely.

**Comment by jacksight** [comment]
This problem has been reported to xina
