### ISSUE TITLE
[Question] Do you plan on releasing A11 support anytime soon?

### ISSUE THREAD

**Issue by ieatbeansbruh** [jacksight/xina520_official_jailbreak#5]

**Comment by MrMan314** [comment]
For A11 there is [palera1n](https://github.com/palera1n/palera1n)

**Comment by Lrive** [comment]
Palera1n needs alot of store in order to jailbreak, aswell as this jailbreak being more stable.

**Comment by jacksight** [comment]
Xina himself said that there is currently no plan to A11 or lower devices, if he got spare time, he would do a research on Fugu15 first, rather than trying to support A11 devices first
