### ISSUE TITLE
Books App Crash

### ISSUE THREAD

**Issue by Marrroooon** [jacksight/xina520_official_jailbreak#50]
While in Jailbreak Mode, Books App doesn’t work properly. Books don’t download, text doesn’t show up, the cover just freezes. Then it says “There was a problem with the content of this book” and a button “Download the book again” appears but doesn’t do anything when pressed. 
The app works fine in NonJail mode.

**Comment by jacksight** [comment]
Um, have you tried in LinTui mode?

**Comment by Marrroooon** [comment]
It works in LinTui (same issue on 1.1.8)

**Comment by jacksight** [comment]
Um, any tweaks installed? Since disabling tweak injection works somwhow
