### ISSUE TITLE
Unable to run custom command tools in iOS terminal, getting Killed 9 error.

### ISSUE THREAD

**Issue by ghostsun89** [jacksight/xina520_official_jailbreak#57]
I built a custom command tool which named ios_test using Theos tools on the MacBook. Using the codesign tools to sign the command tool.
The details are as follows:
```
lipo ios_test -thin arm64 -output ios_test
codesign -s "xxxx" --entitlements ./ent.xml -f ios_test
```
ent.xml is as follows:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>platform-application</key>
	<true/>
</dict>
</plist>
```
And using ssh scp to push the file to the path /var/jb/usr/bin on the jailbreak iPhone using the XinaA15, which version is 1.1.8.
But when I ran the ios_test, I always got the ```Killed: 9``` error.

How can I fix the problem? Thanks.

**Comment by jacksight** [comment]
This was discovered by Ivano a long time ago and was reported to Xina. I think that Ivano came up with a solution, but I'm not sure

**Comment by ghostsun89** [comment]
> This was discovered by Ivano a long time ago and was reported to Xina. I think that Ivano came up with a solution, but I'm not sure

Is there any way to communicate with Ivano to ensure his solution? Thanks. @jacksight

**Comment by jacksight** [comment]
Sure, I'll try to reach him for further solutions
