### ISSUE TITLE
Installment failure 

### ISSUE THREAD

**Issue by MrRabbit71** [jacksight/xina520_official_jailbreak#63]
When trying to install via altserver I get “String to long” and then it’s a failure. Tried many times but same result. 
I have an iPad Pro M1 iOS 16.4.1

**Comment by jacksight** [comment]
Are you using Windows's version of AltServer?

**Comment by MrRabbit71** [comment]
Yes, I am. It has worked before.

**Comment by jacksight** [comment]
It should work if you turn off Anti virus and Windows Defender Firewall

**Comment by MrRabbit71** [comment]
I have altserver on my iPad. It’s then when I’m trying to install xenaA15 2.0 I’m getting “String to long” on my iPad.

**Comment by MrRabbit71** [comment]
Probably but can i do what i want and use with an no JB iPad?

**Comment by jacksight** [comment]
All the IPAs had the same result? Or just for the XinaA15?

**Comment by MrRabbit71** [comment]
My bad…it says “vector to long” and it’s only the XenaA15

I’m using AltServer 1.6.1.0 which is the latest according to AltServer update.

**Comment by MrRabbit71** [comment]
I’m trying sideloadly now…..

**Comment by jacksight** [comment]
Probably just the IPA isn't compatible with AltStore method I assume

**Comment by NightwindDev** [comment]
Hey, @MrRabbit71. 

You mentioned that you are using iPadOS 16.4.1. Not sure if that is a typo, but if it isn't, then XinaA15 will **not** currently work on your device. 

FYI, XinaA15 2.0.13 is currently only compatible with iOS 15.0-15.4.1. TrollStore is also compatible with that same range of iOS versions. Therefore, it is easier to use TrollStore to sideload XinaA15 onto your device.

**Comment by MrRabbit71** [comment]
Well. We do have a MrGeo who said that it would work but as usual he wrong. That explains why it’s not working
