### ISSUE TITLE
Not working on iPad mini 6

### ISSUE THREAD

**Issue by jujhar18** [jacksight/xina520_official_jailbreak#9]
I tried installing , but it shows a green screen and the iPad restarts

**Comment by jacksight** [comment]
Green???? Alright then, I'll report it to xina, also try the updated version on my GitHub

**Comment by optconepiece059** [comment]
does anybody have a fix for ipad mini 6? I'm on ios 15.1 and when i try to jailbreak, it only restarts and no sileo app installed.
